name: CI/CD pipeline 
on: push
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            -name: checkout repo
            uses: actions/checkout@v3

            -name: setup node 
            uses: actions/setup-node@v3
            with:
                node-version: 18

            -name: install npm
            run: npm install
            
            -name: build project
            run: npm run builds
            