name: CI/CD for React App

on:
  push:
    branches: [main]  #It will trigger on push events to the main branch.
 
  workflow_dispatch:   #This allows you to manually trigger
  schedule:
    - cron: "1 * * * *"
  

permissions:
  contents: write


jobs:
  build_and_deploy:
    strategy:
        matrix:
            verion: ["14","16","18","20"]
            os: ["ubuntu-latest"]  
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.version}}

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run folder
       
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: folder